import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lamhaa",
  description: "Generated by Lamhaa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="fancy-fonts">
      <head>
        <title>Lamhaa</title>
        {/* Playfair Display for headings and branding */}
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Geist:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
